version: "3.9"


services:
  config-server:
    container_name: config-server
    image: config-server:v2
    build:
      context: config-server
      dockerfile: Dockerfile
    networks:
      - minibay-network
    ports:
      - "8888:8888"
  eureka-server:
    container_name: eureka-server
    image: eureka-server:v2
    build:
      context: eureka-server
      dockerfile: Dockerfile
    networks:
      - minibay-network
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - config-server
networks:
  minibay-network:
    driver: bridge